### ISSUE TITLE
b is not a function

### ISSUE THREAD

**Issue by earksiinni** [kitten/wonka#108]
I'm using urql in a React app, which pulls in Wonka as a dependency, and I'm getting the following error during SSR on any of my pages that does a GraphQL query:

```
TypeError: b is not a function
at d (webpack-internal:////node_modules/wonka/dist/wonka.mjs:125:203)
at eval (webpack-internal:////node_modules/wonka/dist/wonka.mjs:700:9)
at eval (webpack-internal:////node_modules/urql/dist/urql.es.js:258:15)
at eval (webpack-internal:////node_modules/wonka/dist/wonka.mjs:692:14)
at eval (webpack-internal:////node_modules/wonka/dist/wonka.mjs:136:144)
at _0 (webpack-internal:////node_modules/wonka/dist/wonka.mjs:72:55)
at _0 (webpack-internal:////node_modules/wonka/dist/wonka.mjs:146:32)
at d (webpack-internal:////node_modules/wonka/dist/wonka.mjs:247:140)
at eval (webpack-internal:////node_modules/wonka/dist/wonka.mjs:138:7)
at eval (webpack-internal:////node_modules/wonka/dist/wonka.mjs:257:143)
```

I tried going into `wonka.mjs` as well as `urql.es.js` but they're all optimized and I can't make heads or tails out of the line numbers. I know that it wasn't always throwing this error, and I'm not sure what I changed to break it.

The only thing that I can think of is that I recently installed the `reason-urql` bindings and the `graphql-ppx` for ReScript as I'm migrating my app over to ReasonReact and ReScript. However, I'm not currently using either the bindings or the ppx.

Can anyone help me out? I'm sorry, I know that it's not a lot to go on. This is probably more of a debugging question than it is an issue with the library.

**Comment by earksiinni** [comment]
I confirmed that `reason-urql` and `graphql-ppx` aren't the problem. I removed both packages from `bsconfig.json` and I'm still getting the error.

No error in the browser, this is just during SSR in Node.

**Comment by earksiinni** [comment]
Well, I tried changing enough things in my urql setup that I managed to stumble upon a fix. I set `suspense: false` in my urql configuration object, whereas before it was `suspense: typeof window === 'undefined'`. Not sure why it was set to that in my codebase, but I don't use suspense anyway so it's all good.

Didn't figure out a good way to debug the error. Oh well. Closing.
